# Generated by Django 2.2.10 on 2020-02-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltimediscount',
            name='name',
            field=models.CharField(default='new', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocodediscount',
            name='name',
            field=models.CharField(default='new', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagediscount',
            name='name',
            field=models.CharField(default='new', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporarydiscount',
            name='name',
            field=models.CharField(default='new', max_length=255),
            preserve_default=False,
        ),
    ]
