# Generated by Django 2.2.10 on 2020-02-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20200218_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagediscount',
            name='is_active_user',
            field=models.BooleanField(default=True),
        ),
    ]
