# Generated by Django 2.2.10 on 2020-02-20 08:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')
                 ),
                ('name', models.CharField(max_length=255)),
                ('start_price', models.DecimalField(
                    decimal_places=2, max_digits=7,
                    validators=[django.core.validators.MinValueValidator(1)]
                )
                 ),
                ('create_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')
                 ),
                ('name', models.CharField(max_length=255)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='contenttypes.ContentType')
                 ),
                ('product', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sales', to='manages.Product')
                 ),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')
                 ),
                ('client_phone_number', models.CharField(max_length=30)),
                ('status', models.CharField(
                    choices=[('N', 'New'), ('D', 'Done'), ('P', 'Payed')],
                    default='N', max_length=1)
                 ),
                ('date_create_order', models.DateField()),
                ('date_close_order', models.DateField(
                    blank=True, null=True)
                 ),
                ('product', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='manages.Product')
                 ),
            ],
        ),
    ]
