# Generated by Django 2.2.10 on 2020-02-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="statussale",
            new_name="status_sale",
        ),
    ]
