# Generated by Django 2.2.10 on 2020-02-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
