# Generated by Django 2.2.10 on 2020-02-12 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manages", "0007_auto_20200212_1140"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="sale",),
        migrations.AddField(
            model_name="product",
            name="sale",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="manages.Sale"
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="discount",
            field=models.PositiveIntegerField(
                unique=True,
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
