# Generated by Django 2.2.10 on 2020-02-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manages", "0008_auto_20200212_1311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sale",
            field=models.ManyToManyField(
                blank=True, related_name="sales", to="manages.Sale"
            ),
        ),
    ]
