# Generated by Django 2.2.10 on 2020-02-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manages", "0009_auto_20200212_1317"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sale",
            field=models.ManyToManyField(blank=True, to="manages.Sale"),
        ),
    ]
