# Generated by Django 2.2.10 on 2020-02-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manages", "0015_auto_20200213_0918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_create_order",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
