# Generated by Django 2.2.10 on 2020-02-17 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manages", "0019_auto_20200214_0906"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="discount",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
