# Generated by Django 2.2.10 on 2020-02-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manages', '0022_auto_20200217_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manages.Sale'),
        ),
    ]
