# Generated by Django 2.2.10 on 2020-02-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manages", "0024_remove_sale_discount"),
    ]

    operations = [
        migrations.RemoveField(model_name="sale", name="content_type",),
        migrations.RemoveField(model_name="sale", name="object_id",),
    ]
